# Generated by Django 3.1 on 2020-08-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
